### PR TITLE
buttonmasher-aggregator doesn't deploy

### PR DESCRIPTION
**Pull request by craigbox**
The yaml file needed the --- at the end of the final service, or else it only created the first three.

### CODE REVIEW

**Comment by saturnism** [comment]
That's quite weird - it has always deployed w/o the ending separator. was there something else that could be wrong?

**Comment by craigbox** [comment]
OK, finally figured it out...

```
$ make federation-deploy
cat federated/*.yaml | sed -e 's|FEDERATION_NAME|federation|g' | kubectl --context=federation-cluster apply -f -
service "buttonmasher-frontend" created
service "buttonmasher-backend" created
service "buttonmasher-visualizer" created
replicaset "load-bots" created
```

It's concatenating the two files, so the header of loaders-rs.yaml is being concatenated to create a document with two kind: headers, and only the second one counts.

**Comment by saturnism** [comment]
Ah hah! That's subtle, thanks for finding this.

Rather than fixing the file to make concatenation work, I should prob do this properly by going through one file at a time

**Comment by craigbox** [comment]
Agreed

**Pull request closed without merging**
